import { Event, Ticket, User, Notification, AnalyticsData, Badge } from '@/types';

export const GRADIENTS = [
  'from-[#2CC4EA] to-[#533885]',
  'from-[#FF55C2] to-[#7222E3]',
  'from-[#FFBC73] to-[#FF00B9]',
  'from-[#46FFAB] to-[#A02EFF]',
  'from-[#1D5BFF] to-[#C7FE17]',
  'from-[#DD1FFF] to-[#24D8FB]',
];

export const GRADIENT_STYLES = [
  'linear-gradient(135deg,#2CC4EA,#533885)',
  'linear-gradient(135deg,#FF55C2,#7222E3)',
  'linear-gradient(135deg,#FFBC73,#FF00B9)',
  'linear-gradient(135deg,#46FFAB,#A02EFF)',
  'linear-gradient(135deg,#1D5BFF,#C7FE17)',
  'linear-gradient(135deg,#DD1FFF,#24D8FB)',
];

export const EVENT_IMAGES = [
  'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80',
  'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800&q=80',
  'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80',
  'https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=800&q=80',
  'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80',
  'https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=800&q=80',
  'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800&q=80',
  'https://images.unsplash.com/photo-1571266028243-d220c6a7a01c?w=800&q=80',
];

export const MOCK_EVENTS: Event[] = [
  {
    id: '1', title: 'Dynamos vs CAPS United — PSL Derby', slug: 'dynamos-vs-caps-psl-derby',
    category: 'sports', categoryLabel: 'Sports', date: 'Sat, May 9', dateISO: '2026-05-09',
    time: '3:00 PM', endTime: '5:15 PM', venue: 'National Sports Stadium', address: 'Samora Machel Ave, Harare',
    city: 'Harare', description: 'A high-stakes PSL derby under the Harare afternoon sun. Expect big crowds and bigger moments.',
    longDescription: 'The PSL derby returns to National Sports Stadium. Arrive early for pre-match fan zones, local food vendors, and supporter performances. Family-friendly sections available, plus premium seating with dedicated entry and refreshments.',
    price: 5, priceLabel: '$5', attendees: 18000, capacity: 35000,
    image: EVENT_IMAGES[0], images: [EVENT_IMAGES[0], EVENT_IMAGES[3], EVENT_IMAGES[4]],
    mood: 'energetic', tags: ['psl', 'football', 'harare', 'derby'],
    featured: true, lineup: ['Dynamos FC', 'CAPS United'],
    organizer: 'Premier Soccer League', organizerAvatar: 'PSL',
    lat: -17.8047, lng: 31.0101,
    ticketTiers: [
      { id: 'terrace', name: 'Terrace', price: 5, description: 'Standard entry seating', perks: ['Stadium access', 'Fan zone access'], available: 12000, total: 20000, gradient: GRADIENT_STYLES[0] },
      { id: 'grandstand', name: 'Grandstand', price: 12, description: 'Improved view + faster entry', perks: ['Better seating', 'Priority gates', 'Refreshments nearby'], available: 4500, total: 7000, gradient: GRADIENT_STYLES[1] },
      { id: 'premium', name: 'Premium', price: 30, description: 'Best views + dedicated entrance', perks: ['Dedicated entrance', 'Best seats', 'Refreshments included'], available: 850, total: 1200, gradient: GRADIENT_STYLES[2] },
    ],
    tables: [
      { id: 't1', name: 'Table 1', seats: 6, price: 800, perks: ['Bottle service', 'Private server', 'Priority entry'], available: true, position: { x: 20, y: 30 } },
      { id: 't2', name: 'Table 2', seats: 8, price: 1200, perks: ['2 Bottle service', 'Private server', 'Priority entry', 'Meet & greet'], available: true, position: { x: 55, y: 30 } },
      { id: 't3', name: 'Table 3 (SOLD)', seats: 6, price: 800, perks: ['Bottle service', 'Private server'], available: false, position: { x: 80, y: 30 } },
      { id: 't4', name: 'Table 4', seats: 4, price: 600, perks: ['Bottle service', 'Priority entry'], available: true, position: { x: 20, y: 65 } },
      { id: 't5', name: 'Table 5', seats: 10, price: 2000, perks: ['3 Bottles', 'Private server', 'Chef table', 'Artist access'], available: true, position: { x: 55, y: 65 } },
    ],
    bottleService: [
      { id: 'b1', name: 'Grey Goose Vodka', type: 'Vodka', price: 280, image: '🍾', description: 'Premium French vodka' },
      { id: 'b2', name: 'Don Julio 1942', type: 'Tequila', price: 350, image: '🥃', description: 'Ultra-premium aged tequila' },
      { id: 'b3', name: 'Hennessy XO', type: 'Cognac', price: 420, image: '🍷', description: 'Exceptional cognac blend' },
      { id: 'b4', name: 'Ace of Spades', type: 'Champagne', price: 500, image: '🍾', description: 'Jay-Z\'s legendary champagne' },
      { id: 'b5', name: 'Casamigos Blanco', type: 'Tequila', price: 240, image: '🥃', description: 'George Clooney\'s smooth tequila' },
    ],
  },
  {
    id: '2', title: 'Winky D Live: Gafa Life Experience', slug: 'winky-d-gafa-life-harare',
    category: 'music', categoryLabel: 'Music', date: 'Fri, May 15', dateISO: '2026-05-15',
    time: '7:00 PM', endTime: '11:30 PM', venue: 'Harare International Conference Centre', address: 'Rainbow Towers, Harare',
    city: 'Harare', description: 'A headline Harare show with live band energy, anthems, and premium production.',
    longDescription: 'A premium concert experience at HICC: fast entry lanes, merch stations, and lounge-style VIP seating. Expect a tightly curated setlist, special guests, and a clean, high-signal production design.',
    price: 15, priceLabel: '$15', attendees: 3200, capacity: 4500,
    image: EVENT_IMAGES[1], images: [EVENT_IMAGES[1], EVENT_IMAGES[5]],
    mood: 'energetic', tags: ['concert', 'zimdancehall', 'harare', 'live'],
    featured: true,
    lineup: ['Winky D', 'Special Guests'],
    organizer: 'Gafa Entertainment', organizerAvatar: 'GE',
    lat: -17.8336, lng: 31.0421,
    ticketTiers: [
      { id: 'ga', name: 'General Admission', price: 15, description: 'Concert entry', perks: ['Main floor access', 'Merch access'], available: 900, total: 3000, gradient: GRADIENT_STYLES[0] },
      { id: 'vip', name: 'VIP Lounge', price: 45, description: 'Elevated seating + dedicated entry', perks: ['VIP seating', 'Dedicated entry', '1 drink token'], available: 180, total: 400, gradient: GRADIENT_STYLES[1] },
    ],
    tables: [], bottleService: [],
  },
  {
    id: '3', title: 'Alex Sports Club: Rooftop Sunday Session', slug: 'alex-sports-club-rooftop-sunday',
    category: 'music', categoryLabel: 'Nightlife', date: 'Sun, May 17', dateISO: '2026-05-17',
    time: '4:00 PM', endTime: '10:00 PM', venue: 'Alex Sports Club', address: 'Alexandra Park, Harare',
    city: 'Harare', description: 'Sunset sets, premium cocktails, and a clean rooftop vibe — Harare’s Sunday staple.',
    longDescription: 'A curated Sunday session at Alex Sports Club with rotating DJs, elevated sound, and a premium lounge layout. Book tables early, arrive for golden hour, and keep it smooth through the night.',
    price: 10, priceLabel: '$10', attendees: 620, capacity: 900,
    image: EVENT_IMAGES[3], images: [EVENT_IMAGES[3], EVENT_IMAGES[0]],
    mood: 'social', tags: ['nightlife', 'harare', 'rooftop', 'djs'],
    featured: true,
    lineup: ['Resident DJ', 'Guest DJ'],
    organizer: 'Alex Sports Club', organizerAvatar: 'AS',
    lat: -17.7942, lng: 31.0528,
    ticketTiers: [
      { id: 'entry', name: 'Entry', price: 10, description: 'Standard entry', perks: ['Venue access'], available: 240, total: 700, gradient: GRADIENT_STYLES[2] },
      { id: 'vip', name: 'VIP Table', price: 120, description: 'Reserved table seating', perks: ['Reserved table', 'Priority entry', 'Table service'], available: 8, total: 20, gradient: GRADIENT_STYLES[1] },
    ],
    tables: [
      { id: 't1', name: 'Booth A', seats: 6, price: 600, perks: ['1 Bottle', 'Priority entry'], available: true, position: { x: 15, y: 25 } },
      { id: 't2', name: 'Booth B', seats: 8, price: 900, perks: ['2 Bottles', 'Priority entry'], available: false, position: { x: 50, y: 25 } },
      { id: 't3', name: 'Booth C', seats: 4, price: 400, perks: ['1 Bottle'], available: true, position: { x: 80, y: 25 } },
    ],
    bottleService: [
      { id: 'b1', name: 'Grey Goose', type: 'Vodka', price: 250, image: '🍾', description: 'Premium French vodka' },
      { id: 'b2', name: 'Patron Silver', type: 'Tequila', price: 220, image: '🥃', description: 'Classic silver tequila' },
      { id: 'b3', name: 'Moët & Chandon', type: 'Champagne', price: 180, image: '🥂', description: 'Iconic French champagne' },
    ],
  },
  {
    id: '4', title: 'Sunset Jazz at The Jam Tree', slug: 'sunset-jazz-jam-tree',
    category: 'music', categoryLabel: 'Music', date: 'Thu, May 21', dateISO: '2026-05-21',
    time: '6:30 PM', endTime: '9:30 PM', venue: 'The Jam Tree', address: 'Mount Pleasant, Harare',
    city: 'Harare', description: 'Live jazz, great food, and a premium outdoor atmosphere in Mount Pleasant.',
    longDescription: 'A refined Thursday night with live jazz, a well-paced setlist, and a relaxed crowd. Expect a clean acoustic mix, elevated menus, and a calm premium vibe that still feels alive.',
    price: 8, priceLabel: '$8', attendees: 260, capacity: 420,
    image: EVENT_IMAGES[2], images: [EVENT_IMAGES[2], EVENT_IMAGES[6]],
    mood: 'romantic', tags: ['jazz', 'harare', 'live', 'food'],
    featured: false,
    lineup: ['House Jazz Band'],
    organizer: 'The Jam Tree', organizerAvatar: 'JT',
    lat: -17.7760, lng: 31.0792,
    ticketTiers: [
      { id: 'entry', name: 'Entry', price: 8, description: 'Standard seating', perks: ['Venue access'], available: 120, total: 300, gradient: GRADIENT_STYLES[5] },
      { id: 'reserved', name: 'Reserved', price: 18, description: 'Reserved seating', perks: ['Reserved seat', 'Welcome drink'], available: 40, total: 80, gradient: GRADIENT_STYLES[3] },
    ],
    tables: [], bottleService: [],
  },
  {
    id: '5', title: 'Wellness Flow at Borrowdale Race Course', slug: 'wellness-flow-borrowdale',
    category: 'wellness', categoryLabel: 'Wellness', date: 'Sat, May 30', dateISO: '2026-05-30',
    time: '8:00 AM', endTime: '11:00 AM', venue: 'Borrowdale Race Course', address: 'Borrowdale, Harare',
    city: 'Harare', description: 'A calm Saturday reset: yoga, breathwork, and a short guided walk.',
    longDescription: 'A premium, low-noise wellness morning designed for clarity: guided breathwork, a steady yoga flow, and a short social cooldown. Bring a mat; hydration stations available.',
    price: 6, priceLabel: '$6', attendees: 180, capacity: 260,
    image: EVENT_IMAGES[5], images: [EVENT_IMAGES[5]],
    mood: 'chill', tags: ['wellness', 'yoga', 'harare', 'morning'],
    featured: false,
    lineup: [],
    organizer: 'Wellness Collective', organizerAvatar: 'WC',
    lat: -17.7474, lng: 31.0957,
    ticketTiers: [
      { id: 'standard', name: 'Standard', price: 6, description: 'Session access', perks: ['Yoga flow', 'Breathwork', 'Hydration'], available: 60, total: 200, gradient: GRADIENT_STYLES[3] },
      { id: 'premium', name: 'Premium', price: 15, description: 'Extra comfort + goodies', perks: ['All standard perks', 'Wellness kit', 'Priority check-in'], available: 18, total: 40, gradient: GRADIENT_STYLES[4] },
    ],
    tables: [], bottleService: [],
  },
  {
    id: '6', title: 'Street Food Night Market — Sam Levy’s Village', slug: 'street-food-night-market-sam-levy',
    category: 'food', categoryLabel: 'Food & Drink', date: 'Fri, Jun 5', dateISO: '2026-06-05',
    time: '5:00 PM', endTime: '10:00 PM', venue: 'Sam Levy’s Village', address: 'Borrowdale, Harare',
    city: 'Harare', description: 'Curated street food, local pop-ups, and live sets — a clean Friday plan.',
    longDescription: 'A premium night market experience with curated vendors, clean signage, and clear queues. Expect comfort food, dessert stations, and a small stage with live sets.',
    price: 3, priceLabel: '$3', attendees: 1400, capacity: 3000,
    image: EVENT_IMAGES[6], images: [EVENT_IMAGES[6], EVENT_IMAGES[7]],
    mood: 'social', tags: ['food', 'harare', 'market', 'night'],
    featured: false,
    lineup: [],
    organizer: 'Village Events', organizerAvatar: 'VE',
    lat: -17.7606, lng: 31.1018,
    ticketTiers: [
      { id: 'entry', name: 'Entry', price: 3, description: 'Market entry', perks: ['Vendor access', 'Live sets'], available: 1200, total: 2600, gradient: GRADIENT_STYLES[2] },
      { id: 'fast', name: 'Fast Lane', price: 8, description: 'Faster entry + perks', perks: ['Fast entry', '1 drink token'], available: 220, total: 400, gradient: GRADIENT_STYLES[1] },
    ],
    tables: [], bottleService: [],
  },
  {
    id: '7', title: 'First Fridays: Art + Live Sessions', slug: 'first-fridays-art-live-sessions',
    category: 'art', categoryLabel: 'Art & Culture', date: 'Fri, Jun 12', dateISO: '2026-06-12',
    time: '5:30 PM', endTime: '9:00 PM', venue: 'National Gallery of Zimbabwe', address: '20 Julius Nyerere Way, Harare',
    city: 'Harare', description: 'A curated after-hours art experience with live sessions and a relaxed social vibe.',
    longDescription: 'Explore rotating exhibitions with a soft after-hours program: live sessions, short artist talks, and a clean flow through galleries. Ideal for dates, groups, and anyone who wants culture without noise.',
    price: 0, priceLabel: 'Free', attendees: 520, capacity: 900,
    image: EVENT_IMAGES[7], images: [EVENT_IMAGES[7]],
    mood: 'chill', tags: ['art', 'culture', 'harare', 'free'],
    featured: false,
    lineup: [],
    organizer: 'National Gallery', organizerAvatar: 'NG',
    lat: -17.8293, lng: 31.0536,
    ticketTiers: [
      { id: 'free', name: 'Free Entry', price: 0, description: 'Gallery access', perks: ['Gallery access', 'Live sessions'], available: 600, total: 900, gradient: GRADIENT_STYLES[0] },
      { id: 'guided', name: 'Guided Tour', price: 7, description: 'Curated walkthrough', perks: ['Guided tour', 'Artist Q&A'], available: 45, total: 80, gradient: GRADIENT_STYLES[5] },
    ],
    tables: [], bottleService: [],
  },
  {
    id: '8', title: 'Belgravia Nightlife Circuit: Friday Pass', slug: 'belgravia-nightlife-circuit-friday',
    category: 'music', categoryLabel: 'Nightlife', date: 'Fri, Jun 19', dateISO: '2026-06-19',
    time: '9:00 PM', endTime: '3:00 AM', venue: 'Belgravia (Multi-venue)', address: 'Belgravia, Harare',
    city: 'Harare', description: 'One pass, curated venues, clear entry flow — premium Harare nightlife without friction.',
    longDescription: 'A curated multi-venue pass designed for smooth movement: clear entry, partner venues, and optional VIP upgrades. Built for groups who want options without the chaos.',
    price: 12, priceLabel: '$12', attendees: 900, capacity: 1400,
    image: EVENT_IMAGES[4], images: [EVENT_IMAGES[4]],
    mood: 'energetic', tags: ['nightlife', 'harare', 'belgravia', 'friday'],
    featured: false,
    lineup: [],
    organizer: 'Night Circuit', organizerAvatar: 'NC',
    lat: -17.8129, lng: 31.0502,
    ticketTiers: [
      { id: 'pass', name: 'Entry Pass', price: 12, description: 'Partner venues entry', perks: ['Entry pass', 'Partner venues'], available: 320, total: 900, gradient: GRADIENT_STYLES[4] },
      { id: 'vip', name: 'VIP Upgrade', price: 35, description: 'Fast entry + VIP perks', perks: ['Fast entry', 'VIP lounge access'], available: 60, total: 120, gradient: GRADIENT_STYLES[1] },
    ],
    tables: [], bottleService: [],
  },
];

export const MOCK_USER: User = {
  id: 'u1', name: 'Alex Johnson', email: 'alex@eventsdistro.com', avatar: '', avatarColor: '#7B61FF', initials: 'AJ',
  bio: 'Music lover, night owl, festival addict. Always chasing the next great experience.',
  location: 'Harare, Zimbabwe', joinedAt: '2024-03-15', loyaltyPoints: 2840,
  eventsAttended: 23, totalSpent: 1250, isVip: true, role: 'event_manager',
  badges: [
    { id: 'explorer', name: 'Top Explorer', icon: '🦅', description: 'Attended 10+ events this month', earned: true, earnedAt: '2026-04-01' },
    { id: 'early-bird', name: 'Early Bird', icon: '⚡', description: 'First 100 to book 5 events', earned: true, earnedAt: '2026-03-15' },
    { id: 'culture', name: 'Culture Seeker', icon: '🎭', description: 'Explored 5 different categories', earned: true, earnedAt: '2026-02-20' },
    { id: 'globe', name: 'Globe Trotter', icon: '🌍', description: 'Attended events in 3+ cities', earned: false },
    { id: 'nightowl', name: 'Night Owl', icon: '🦉', description: 'Attended 5+ late night events', earned: true, earnedAt: '2026-04-10' },
    { id: 'vip', name: 'VIP Elite', icon: '👑', description: 'Spent $1000+ on VIP tickets', earned: true, earnedAt: '2026-04-15' },
  ],
};

export const MOCK_TICKETS: Ticket[] = [
  {
    id: 'tk1', ticketId: 'ED-1746300001-A3F9', eventId: '1', event: MOCK_EVENTS[0],
    tier: MOCK_EVENTS[0].ticketTiers[1], quantity: 2, totalAmount: 240,
    purchasedAt: '2026-04-20T14:32:00Z', status: 'upcoming',
    qrCode: 'ED-1746300001-A3F9', holderName: 'Alex Johnson', holderEmail: 'alex@eventsdistro.com',
  },
  {
    id: 'tk2', ticketId: 'ED-1746300002-B7K2', eventId: '3', event: MOCK_EVENTS[2],
    tier: MOCK_EVENTS[2].ticketTiers[0], quantity: 1, totalAmount: 30,
    purchasedAt: '2026-04-22T09:15:00Z', status: 'upcoming',
    qrCode: 'ED-1746300002-B7K2', holderName: 'Alex Johnson', holderEmail: 'alex@eventsdistro.com',
  },
  {
    id: 'tk3', ticketId: 'ED-1746300003-C4M8', eventId: '4', event: MOCK_EVENTS[3],
    tier: MOCK_EVENTS[3].ticketTiers[1], quantity: 1, totalAmount: 95,
    purchasedAt: '2026-03-10T18:00:00Z', status: 'past',
    qrCode: 'ED-1746300003-C4M8', holderName: 'Alex Johnson', holderEmail: 'alex@eventsdistro.com',
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  { id: 'n1', type: 'reminder', title: 'Event Tomorrow!', message: 'Neon Dreams Festival is tomorrow at 8PM. Don\'t forget your ticket!', time: '2 hours ago', read: false, eventId: '1' },
  { id: 'n2', type: 'ticket', title: 'Ticket Confirmed', message: 'Your VIP tickets for Neon Dreams Festival have been confirmed. Check your tickets page.', time: '3 days ago', read: false, eventId: '1' },
  { id: 'n3', type: 'promo', title: '🔥 Flash Sale — 30% Off', message: 'Limited time: Get 30% off Jazz Under The Stars VIP tickets. Use code JAZZ30.', time: '5 days ago', read: true, eventId: '4' },
  { id: 'n4', type: 'update', title: 'Lineup Update', message: 'Fred Again.. has been added to the Neon Dreams Festival lineup!', time: '1 week ago', read: true, eventId: '1' },
  { id: 'n5', type: 'system', title: '🎉 You Earned a Badge!', message: 'You earned the "Night Owl" badge for attending 5 late night events.', time: '1 week ago', read: true },
  { id: 'n6', type: 'promo', title: 'New Event Near You', message: 'Warehouse Rave: Afterhours just dropped. Early bird tickets available now.', time: '2 weeks ago', read: true, eventId: '3' },
];

export const ANALYTICS_DATA: AnalyticsData[] = [
  { date: 'Jan', tickets: 120, revenue: 5400, attendance: 110 },
  { date: 'Feb', tickets: 200, revenue: 9000, attendance: 185 },
  { date: 'Mar', tickets: 350, revenue: 15750, attendance: 330 },
  { date: 'Apr', tickets: 480, revenue: 21600, attendance: 455 },
  { date: 'May', tickets: 620, revenue: 27900, attendance: 589 },
  { date: 'Jun', tickets: 540, revenue: 24300, attendance: 510 },
  { date: 'Jul', tickets: 780, revenue: 35100, attendance: 741 },
  { date: 'Aug', tickets: 920, revenue: 41400, attendance: 874 },
];

export const HIGH_SPENDERS = [
  { name: 'Marcus R.', email: 'marcus@email.com', spent: 2400, tickets: 8, badge: '👑 VIP Elite' },
  { name: 'Sofia K.', email: 'sofia@email.com', spent: 1890, tickets: 6, badge: '🦅 Top Explorer' },
  { name: 'James T.', email: 'james@email.com', spent: 1650, tickets: 5, badge: '⚡ Early Bird' },
  { name: 'Luna P.', email: 'luna@email.com', spent: 1400, tickets: 7, badge: '🎭 Culture Seeker' },
  { name: 'Alex J.', email: 'alex@eventsdistro.com', spent: 1250, tickets: 4, badge: '🦉 Night Owl' },
];
