-- ============================================================
-- Migration 004: Core Postgres functions
-- Future Times Events Platform
-- Created: 2026-07-20
-- ============================================================
--
-- All functions use SECURITY DEFINER with explicit search_path
-- to prevent search_path injection attacks.
-- ============================================================

BEGIN;

-- ── Helper: get the role of the currently authenticated user ─
CREATE OR REPLACE FUNCTION public.get_my_role()
RETURNS TEXT
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT role FROM public.profiles WHERE id = auth.uid();
$$;

-- ── Helper: check if user is staff for a specific event ──────
CREATE OR REPLACE FUNCTION public.is_event_staff(p_event_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.event_staff
    WHERE event_id = p_event_id
      AND user_id  = auth.uid()
      AND is_active = TRUE
  )
  OR EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid()
      AND role IN ('admin', 'super_admin')
  );
$$;

-- ── ATOMIC TICKET CLAIM ──────────────────────────────────────
--
-- Performs:
--   1. Idempotency check (returns existing ticket if key matches)
--   2. Ticket type validation + claim window check
--   3. Per-contact claim limit enforcement
--   4. Capacity check with row lock (FOR UPDATE)
--   5. Atomic decrement of quantity_available
--   6. ticket_claims insert
--   7. tickets insert with the provided qr_token_hash
--   8. audit_log insert
--
-- The qr_token_hash and ticket_number are generated by the
-- application server BEFORE calling this function, because
-- Node.js crypto is better suited for high-entropy random
-- generation than pg's pgcrypto for this purpose.
--
CREATE OR REPLACE FUNCTION public.claim_ticket_atomic(
  p_event_id           UUID,
  p_ticket_type_id     UUID,
  p_attendee_name      TEXT,
  p_attendee_email     TEXT,
  p_attendee_phone     TEXT     DEFAULT NULL,
  p_quantity           INTEGER  DEFAULT 1,
  p_idempotency_key    TEXT     DEFAULT NULL,
  p_show_in_whos_going BOOLEAN  DEFAULT FALSE,
  p_marketing_opt_in   BOOLEAN  DEFAULT FALSE,
  p_qr_token_hash      TEXT     DEFAULT NULL,  -- SHA-256 hex of the raw token
  p_ticket_number      TEXT     DEFAULT NULL   -- human-readable ticket number
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_ticket_type   public.ticket_types%ROWTYPE;
  v_event         public.events%ROWTYPE;
  v_existing_qty  INTEGER;
  v_claim_id      UUID;
  v_ticket_id     UUID;
  v_ticket_num    TEXT;
BEGIN
  -- ── Idempotency: return early if already claimed ──────────
  IF p_idempotency_key IS NOT NULL THEN
    SELECT tc.id INTO v_claim_id
    FROM public.ticket_claims tc
    WHERE tc.idempotency_key = p_idempotency_key;

    IF FOUND THEN
      SELECT t.id, t.ticket_number INTO v_ticket_id, v_ticket_num
      FROM public.tickets t
      WHERE t.claim_id = v_claim_id
      LIMIT 1;

      RETURN jsonb_build_object(
        'result',        'already_claimed',
        'claim_id',      v_claim_id,
        'ticket_id',     v_ticket_id,
        'ticket_number', v_ticket_num
      );
    END IF;
  END IF;

  -- ── Fetch and lock the ticket type row ───────────────────
  SELECT * INTO v_ticket_type
  FROM public.ticket_types
  WHERE id = p_ticket_type_id AND event_id = p_event_id AND is_active = TRUE
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('result', 'invalid_ticket_type');
  END IF;

  -- ── Fetch event ──────────────────────────────────────────
  SELECT * INTO v_event FROM public.events WHERE id = p_event_id;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('result', 'event_not_found');
  END IF;

  IF v_event.status NOT IN ('published', 'sold_out') THEN
    RETURN jsonb_build_object('result', 'event_not_available', 'status', v_event.status);
  END IF;

  -- ── Check claim window ───────────────────────────────────
  IF v_ticket_type.claim_opens_at IS NOT NULL AND NOW() < v_ticket_type.claim_opens_at THEN
    RETURN jsonb_build_object(
      'result', 'claim_not_open',
      'opens_at', v_ticket_type.claim_opens_at
    );
  END IF;

  IF v_ticket_type.claim_closes_at IS NOT NULL AND NOW() > v_ticket_type.claim_closes_at THEN
    RETURN jsonb_build_object('result', 'claim_closed');
  END IF;

  -- ── Per-contact limit ────────────────────────────────────
  IF v_ticket_type.claim_limit_per_contact > 0 THEN
    SELECT COALESCE(SUM(t.quantity), 0) INTO v_existing_qty
    FROM public.tickets t
    WHERE t.ticket_type_id = p_ticket_type_id
      AND lower(t.attendee_email) = lower(p_attendee_email)
      AND t.status NOT IN ('cancelled', 'revoked');

    IF v_existing_qty + p_quantity > v_ticket_type.claim_limit_per_contact THEN
      RETURN jsonb_build_object(
        'result', 'claim_limit_exceeded',
        'limit',  v_ticket_type.claim_limit_per_contact,
        'held',   v_existing_qty
      );
    END IF;
  END IF;

  -- ── Capacity check ───────────────────────────────────────
  IF v_ticket_type.quantity_available < p_quantity THEN
    RETURN jsonb_build_object(
      'result',    'sold_out',
      'available', v_ticket_type.quantity_available
    );
  END IF;

  -- ── Decrement availability ───────────────────────────────
  UPDATE public.ticket_types
  SET quantity_available = quantity_available - p_quantity,
      updated_at = NOW()
  WHERE id = p_ticket_type_id;

  -- Mark event sold_out if now at zero
  IF (v_ticket_type.quantity_available - p_quantity) = 0 THEN
    UPDATE public.events SET status = 'sold_out' WHERE id = p_event_id;
  END IF;

  -- ── Ticket number ────────────────────────────────────────
  v_ticket_num := COALESCE(
    p_ticket_number,
    'FTE-' || upper(substring(encode(gen_random_bytes(4), 'hex') for 8))
  );

  -- ── Insert claim record ──────────────────────────────────
  INSERT INTO public.ticket_claims (
    event_id, ticket_type_id, quantity,
    attendee_name, attendee_email, attendee_phone,
    idempotency_key, show_in_whos_going, marketing_opt_in,
    terms_accepted_at, status
  ) VALUES (
    p_event_id, p_ticket_type_id, p_quantity,
    p_attendee_name, lower(p_attendee_email), p_attendee_phone,
    p_idempotency_key, p_show_in_whos_going, p_marketing_opt_in,
    NOW(), 'confirmed'
  ) RETURNING id INTO v_claim_id;

  -- ── Insert ticket ────────────────────────────────────────
  INSERT INTO public.tickets (
    ticket_number, event_id, ticket_type_id, claim_id,
    attendee_name, attendee_email, attendee_phone,
    qr_token_hash, quantity, status, issued_at
  ) VALUES (
    v_ticket_num, p_event_id, p_ticket_type_id, v_claim_id,
    p_attendee_name, lower(p_attendee_email), p_attendee_phone,
    p_qr_token_hash, p_quantity, 'issued', NOW()
  ) RETURNING id INTO v_ticket_id;

  -- ── attendee_visibility record (default hidden) ───────────
  INSERT INTO public.attendee_visibility (ticket_id, event_id, is_visible)
  VALUES (v_ticket_id, p_event_id, p_show_in_whos_going)
  ON CONFLICT (ticket_id) DO NOTHING;

  -- ── Audit log ─────────────────────────────────────────────
  INSERT INTO public.audit_logs (actor_id, action, entity_type, entity_id, after_state)
  VALUES (
    auth.uid(), 'ticket.claim', 'ticket', v_ticket_id,
    jsonb_build_object(
      'ticket_number', v_ticket_num,
      'event_id',      p_event_id,
      'quantity',      p_quantity,
      'attendee_email_hash', encode(digest(lower(p_attendee_email), 'sha256'), 'hex')
    )
  );

  RETURN jsonb_build_object(
    'result',        'success',
    'claim_id',      v_claim_id,
    'ticket_id',     v_ticket_id,
    'ticket_number', v_ticket_num
  );
END;
$$;


-- ── ATOMIC CHECK-IN ──────────────────────────────────────────
--
-- Performs:
--   1. Finds ticket by SHA-256 hash of the presented QR token
--   2. Locks the row (FOR UPDATE) — concurrent scans serialize here
--   3. Validates: event match, status, event open
--   4. Atomically marks checked_in
--   5. Inserts ticket_scans record
--   6. Returns structured JSON result
--
-- Result codes:
--   valid_checked_in   — first successful scan, welcome in!
--   already_checked_in — second+ scan of same ticket
--   not_found          — token hash not in database
--   wrong_event        — ticket is for a different event
--   cancelled          — ticket was cancelled
--   revoked            — ticket was revoked
--   event_not_open     — event check-in window not active
--
CREATE OR REPLACE FUNCTION public.verify_and_checkin(
  p_token_hash TEXT,
  p_scanner_id UUID,
  p_event_id   UUID,
  p_gate       TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_ticket      public.tickets%ROWTYPE;
  v_event       public.events%ROWTYPE;
  v_scan_id     UUID;
  v_result_code TEXT;
BEGIN
  -- ── Validate token format (basic sanity) ──────────────────
  IF p_token_hash IS NULL OR length(p_token_hash) < 32 THEN
    INSERT INTO public.ticket_scans (
      event_id, scanner_id, gate, scan_result
    ) VALUES (
      p_event_id, p_scanner_id, p_gate, 'invalid_token'
    );
    RETURN jsonb_build_object('result', 'invalid_token');
  END IF;

  -- ── Find and LOCK the ticket row ──────────────────────────
  -- FOR UPDATE acquires a row-level lock.
  -- Concurrent calls with the same token will block here
  -- until the first transaction commits — then see 'already_checked_in'.
  SELECT * INTO v_ticket
  FROM public.tickets
  WHERE qr_token_hash = p_token_hash
  FOR UPDATE;

  IF NOT FOUND THEN
    INSERT INTO public.ticket_scans (
      event_id, scanner_id, gate, scan_result
    ) VALUES (
      p_event_id, p_scanner_id, p_gate, 'not_found'
    );
    RETURN jsonb_build_object('result', 'not_found');
  END IF;

  -- ── Verify event match ────────────────────────────────────
  IF v_ticket.event_id <> p_event_id THEN
    INSERT INTO public.ticket_scans (
      ticket_id, event_id, scanner_id, gate, scan_result
    ) VALUES (
      v_ticket.id, p_event_id, p_scanner_id, p_gate, 'wrong_event'
    );
    RETURN jsonb_build_object('result', 'wrong_event');
  END IF;

  -- ── Fetch event for window check ─────────────────────────
  SELECT * INTO v_event FROM public.events WHERE id = p_event_id;

  IF v_event.status NOT IN ('published', 'sold_out', 'completed') THEN
    INSERT INTO public.ticket_scans (
      ticket_id, event_id, scanner_id, gate, scan_result
    ) VALUES (
      v_ticket.id, p_event_id, p_scanner_id, p_gate, 'event_not_open'
    );
    RETURN jsonb_build_object('result', 'event_not_open', 'event_status', v_event.status);
  END IF;

  -- ── Handle non-issued statuses ────────────────────────────
  IF v_ticket.status = 'checked_in' THEN
    INSERT INTO public.ticket_scans (
      ticket_id, event_id, scanner_id, gate, scan_result
    ) VALUES (
      v_ticket.id, p_event_id, p_scanner_id, p_gate, 'already_checked_in'
    );
    RETURN jsonb_build_object(
      'result',          'already_checked_in',
      'checked_in_at',   v_ticket.checked_in_at,
      'gate',            v_ticket.gate,
      'attendee_name',   v_ticket.attendee_name,
      'ticket_number',   v_ticket.ticket_number
    );
  END IF;

  IF v_ticket.status = 'cancelled' THEN
    v_result_code := 'cancelled';
    INSERT INTO public.ticket_scans (
      ticket_id, event_id, scanner_id, gate, scan_result
    ) VALUES (
      v_ticket.id, p_event_id, p_scanner_id, p_gate, v_result_code
    );
    RETURN jsonb_build_object('result', v_result_code);
  END IF;

  IF v_ticket.status = 'revoked' THEN
    v_result_code := 'revoked';
    INSERT INTO public.ticket_scans (
      ticket_id, event_id, scanner_id, gate, scan_result
    ) VALUES (
      v_ticket.id, p_event_id, p_scanner_id, p_gate, v_result_code
    );
    RETURN jsonb_build_object('result', v_result_code);
  END IF;

  IF v_ticket.status <> 'issued' THEN
    INSERT INTO public.ticket_scans (
      ticket_id, event_id, scanner_id, gate, scan_result
    ) VALUES (
      v_ticket.id, p_event_id, p_scanner_id, p_gate, 'invalid_status'
    );
    RETURN jsonb_build_object('result', 'invalid_status', 'status', v_ticket.status);
  END IF;

  -- ── ATOMIC CHECK-IN — the money shot ─────────────────────
  UPDATE public.tickets
  SET
    status        = 'checked_in',
    checked_in_at = NOW(),
    checked_in_by = p_scanner_id,
    gate          = p_gate,
    updated_at    = NOW()
  WHERE id = v_ticket.id;

  -- Insert scan record inside the same transaction
  INSERT INTO public.ticket_scans (
    ticket_id, event_id, scanner_id, gate, scan_result
  ) VALUES (
    v_ticket.id, p_event_id, p_scanner_id, p_gate, 'valid_checked_in'
  ) RETURNING id INTO v_scan_id;

  -- Audit log
  INSERT INTO public.audit_logs (actor_id, action, entity_type, entity_id, after_state)
  VALUES (
    p_scanner_id, 'ticket.checkin', 'ticket', v_ticket.id,
    jsonb_build_object(
      'gate',          p_gate,
      'scan_id',       v_scan_id,
      'ticket_number', v_ticket.ticket_number,
      'checked_in_at', NOW()
    )
  );

  RETURN jsonb_build_object(
    'result',          'valid_checked_in',
    'ticket_number',   v_ticket.ticket_number,
    'attendee_name',   v_ticket.attendee_name,
    'ticket_type_id',  v_ticket.ticket_type_id,
    'checked_in_at',   NOW(),
    'scan_id',         v_scan_id
  );
END;
$$;

COMMIT;
